spring:
  application:
    name: url-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  datasource:
#    url: jdbc:mysql://MYSQL-TPXTEST:9090/TEST
#    password: default
#    username: default
#    driver-class-name: com.mysql.cj.jdbc.Driver